on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date for the portfolio generation (format: YYYY-MM-DD)"
        required: false
        default: ""

jobs:
  generate-portfolio:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Generate portfolio
        run: |
          mkdir -p artifacts
          if [ -z "${{ github.event.inputs.date }}" ]; then
            DATE=$(date +%Y-%m-%d)
          else
            DATE=${{ github.event.inputs.date }}
          fi
          python generate_portfolio.py "$DATE"
          cp artifacts/portfolio.json "artifacts/portfolio_${DATE}.json"

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add artifacts/portfolio.json
          git add artifacts/portfolio_*.json
          git commit -m "Update portfolio for $(date +'%Y-%m-%d')"
          git push origin master

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-artifact-${{ github.run_id }}
          path: artifacts/portfolio.json

      - name: Upload dated artifact
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-artifact-dated-${{ github.run_id }}
          path: artifacts/portfolio_*.json
